detector:
  type : grounding_dino
  model_config_path : 'libs/detectors/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py'
  weight_path : 'libs/assets/weights/groundingdino_swint_ogc.pth'
  classes : ["person"]
  box_threshold : 0.3
  text_threshol : 0.25
  device : "cuda"
  self.with_nms : True
  self.nms_treshold : 0.5

handler:
  - type : "ScreenHandler"
    view_w : 1280
    view_h : 720

  - type : "LogHandler"
    dir : "./logs"
    file_name : "dino_results.csv"