detector: 
  type : "YOLOWorld"
  weight_path : "assets/weights/yolo8s-world.pt"
  conf : 0.25
  iou : 0.7
  imgsz : 640
  classes : ["white shirts"]

handler:
  - type : "ScreenHandler"
    view_w : 1280
    view_h : 720

  - type : "LogHandler"
    dir : "./logs"
    file_name : "yoloworld_results_log.csv"

sources:
  - type : 'ImageSource'
    assets_path : "assets/images"
    pattern : "*.jpg"
    fps : 30